// <auto-generated />
using System;
using GpxAnalyzer.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GpxAnalyzer.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260901073913_AddProcessingLeasesOAuthStatesAndPerUserExternalActivityUniqueness")]
    partial class AddProcessingLeasesOAuthStatesAndPerUserExternalActivityUniqueness
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.19");

            modelBuilder.Entity("GpxAnalyzer.Api.Entities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AiReportJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("CalorieMethod")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectedSubType")
                        .HasColumnType("TEXT");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("REAL");

                    b.Property<double>("ElevationGainM")
                        .HasColumnType("REAL");

                    b.Property<double>("ElevationLossM")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<double?>("EstimatedCalories")
                        .HasColumnType("REAL");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FixAnomaliesOnNextRun")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GpxFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("MovingTimeSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PerceivedExertion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ProcessingLeaseExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProcessingLeaseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SplitsJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackGeoJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StartTime");

                    b.HasIndex("Status");

                    b.HasIndex("UserId", "StartTime");

                    b.HasIndex("UserId", "Source", "ExternalId")
                        .IsUnique();

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("GpxAnalyzer.Api.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreferredUnits")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfilePhotoPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("GpxAnalyzer.Api.Entities.AthleteProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Ftp")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("HeightCm")
                        .HasColumnType("REAL");

                    b.Property<int?>("MaxHeartRate")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RestingHeartRate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sex")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Vo2Max")
                        .HasColumnType("REAL");

                    b.Property<double?>("WeightKg")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("AthleteProfiles");
                });

            modelBuilder.Entity("GpxAnalyzer.Api.Entities.GlobalSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("GlobalSettings");
                });

            modelBuilder.Entity("GpxAnalyzer.Api.Entities.Integration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalUserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TokenExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebhookSubscriptionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Provider")
                        .IsUnique();

                    b.ToTable("Integrations");
                });

            modelBuilder.Entity("GpxAnalyzer.Api.Entities.NutritionProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .HasColumnType("TEXT");

                    b.Property<double?>("CaffeineG")
                        .HasColumnType("REAL");

                    b.Property<double>("CaloriesKcal")
                        .HasColumnType("REAL");

                    b.Property<double>("CarbsG")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("FatsG")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ProteinsG")
                        .HasColumnType("REAL");

                    b.Property<double?>("SodiumMg")
                        .HasColumnType("REAL");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("VolumeML")
                        .HasColumnType("REAL");

                    b.Property<double?>("WeightG")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Type");

                    b.ToTable("NutritionProducts");
                });

            modelBuilder.Entity("GpxAnalyzer.Api.Entities.OAuthState", b =>
                {
                    b.Property<string>("Nonce")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Nonce");

                    b.ToTable("OAuthStates");
                });

            modelBuilder.Entity("GpxAnalyzer.Api.Entities.RacePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("REAL");

                    b.Property<double>("ElevationGainM")
                        .HasColumnType("REAL");

                    b.Property<double>("ElevationLossM")
                        .HasColumnType("REAL");

                    b.Property<string>("EquipmentJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LinkedActivityId")
                        .HasColumnType("TEXT");

                    b.Property<double>("MaxElevationM")
                        .HasColumnType("REAL");

                    b.Property<double>("MinElevationM")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PerformanceCoefficient")
                        .HasColumnType("REAL");

                    b.Property<string>("PointsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RaceDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RouteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShareToken")
                        .HasColumnType("TEXT");

                    b.Property<double?>("StartLatitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("StartLongitude")
                        .HasColumnType("REAL");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("SweatRateMLPerHour")
                        .HasColumnType("REAL");

                    b.Property<int?>("TargetTimeBSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TargetTimeCSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TargetTimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ShareToken");

                    b.HasIndex("Status");

                    b.HasIndex("UserId", "UpdatedAt");

                    b.ToTable("RacePlans");
                });

            modelBuilder.Entity("GpxAnalyzer.Api.Entities.RacePlanCheckpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CrewNotes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CutoffTimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("REAL");

                    b.Property<string>("DropBagContentsJson")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ElevationM")
                        .HasColumnType("REAL");

                    b.Property<string>("EquipmentLeaveJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("EquipmentTakeJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasDropBag")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCrewAccessible")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlannedPauseSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RacePlanId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TargetArrivalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RacePlanId", "Order");

                    b.ToTable("RacePlanCheckpoints");
                });

            modelBuilder.Entity("GpxAnalyzer.Api.Entities.RacePlanNutritionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AtCheckpointId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FromCheckpointId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL");

                    b.Property<Guid>("RacePlanId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TimeOffsetSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ToCheckpointId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AtCheckpointId");

                    b.HasIndex("FromCheckpointId");

                    b.HasIndex("ProductId");

                    b.HasIndex("RacePlanId");

                    b.HasIndex("ToCheckpointId");

                    b.ToTable("RacePlanNutritionItems");
                });

            modelBuilder.Entity("GpxAnalyzer.Api.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Token");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("GpxAnalyzer.Api.Entities.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("REAL");

                    b.Property<double>("ElevationGainM")
                        .HasColumnType("REAL");

                    b.Property<double>("ElevationLossM")
                        .HasColumnType("REAL");

                    b.Property<double>("EstimatedTimeSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("MaxElevationM")
                        .HasColumnType("REAL");

                    b.Property<double>("MinElevationM")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PointsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("PoisJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RouteCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoutingProfile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceActivityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WaypointsJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivityType");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("UserId", "UpdatedAt");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("GpxAnalyzer.Api.Entities.Setting", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GpxAnalyzer.Api.Entities.Activity", b =>
                {
                    b.HasOne("GpxAnalyzer.Api.Entities.ApplicationUser", "User")
                        .WithMany("Activities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GpxAnalyzer.Api.Entities.AthleteProfile", b =>
                {
                    b.HasOne("GpxAnalyzer.Api.Entities.ApplicationUser", "User")
                        .WithOne("AthleteProfile")
                        .HasForeignKey("GpxAnalyzer.Api.Entities.AthleteProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GpxAnalyzer.Api.Entities.Integration", b =>
                {
                    b.HasOne("GpxAnalyzer.Api.Entities.ApplicationUser", "User")
                        .WithMany("Integrations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GpxAnalyzer.Api.Entities.NutritionProduct", b =>
                {
                    b.HasOne("GpxAnalyzer.Api.Entities.ApplicationUser", null)
                        .WithMany("NutritionProducts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GpxAnalyzer.Api.Entities.RacePlan", b =>
                {
                    b.HasOne("GpxAnalyzer.Api.Entities.ApplicationUser", "User")
                        .WithMany("RacePlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GpxAnalyzer.Api.Entities.RacePlanCheckpoint", b =>
                {
                    b.HasOne("GpxAnalyzer.Api.Entities.RacePlan", "RacePlan")
                        .WithMany("Checkpoints")
                        .HasForeignKey("RacePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RacePlan");
                });

            modelBuilder.Entity("GpxAnalyzer.Api.Entities.RacePlanNutritionItem", b =>
                {
                    b.HasOne("GpxAnalyzer.Api.Entities.RacePlanCheckpoint", "AtCheckpoint")
                        .WithMany("NutritionAtCheckpoint")
                        .HasForeignKey("AtCheckpointId");

                    b.HasOne("GpxAnalyzer.Api.Entities.RacePlanCheckpoint", "FromCheckpoint")
                        .WithMany("NutritionFromCheckpoint")
                        .HasForeignKey("FromCheckpointId");

                    b.HasOne("GpxAnalyzer.Api.Entities.NutritionProduct", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("GpxAnalyzer.Api.Entities.RacePlan", "RacePlan")
                        .WithMany("NutritionItems")
                        .HasForeignKey("RacePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GpxAnalyzer.Api.Entities.RacePlanCheckpoint", "ToCheckpoint")
                        .WithMany("NutritionToCheckpoint")
                        .HasForeignKey("ToCheckpointId");

                    b.Navigation("AtCheckpoint");

                    b.Navigation("FromCheckpoint");

                    b.Navigation("Product");

                    b.Navigation("RacePlan");

                    b.Navigation("ToCheckpoint");
                });

            modelBuilder.Entity("GpxAnalyzer.Api.Entities.RefreshToken", b =>
                {
                    b.HasOne("GpxAnalyzer.Api.Entities.ApplicationUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GpxAnalyzer.Api.Entities.Route", b =>
                {
                    b.HasOne("GpxAnalyzer.Api.Entities.ApplicationUser", "User")
                        .WithMany("Routes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GpxAnalyzer.Api.Entities.Setting", b =>
                {
                    b.HasOne("GpxAnalyzer.Api.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("GpxAnalyzer.Api.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("GpxAnalyzer.Api.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GpxAnalyzer.Api.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("GpxAnalyzer.Api.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GpxAnalyzer.Api.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("AthleteProfile");

                    b.Navigation("Integrations");

                    b.Navigation("NutritionProducts");

                    b.Navigation("RacePlans");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Routes");
                });

            modelBuilder.Entity("GpxAnalyzer.Api.Entities.RacePlan", b =>
                {
                    b.Navigation("Checkpoints");

                    b.Navigation("NutritionItems");
                });

            modelBuilder.Entity("GpxAnalyzer.Api.Entities.RacePlanCheckpoint", b =>
                {
                    b.Navigation("NutritionAtCheckpoint");

                    b.Navigation("NutritionFromCheckpoint");

                    b.Navigation("NutritionToCheckpoint");
                });
#pragma warning restore 612, 618
        }
    }
}
